# Generated by Django 6.0.2 on 2026-02-26 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('tamil_name', models.CharField(max_length=100)),
                ('image', models.URLField(max_length=500)),
                ('path', models.CharField(max_length=100)),
                ('essence', models.CharField(max_length=200)),
                ('specialty', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('tagline', models.TextField(blank=True, null=True)),
                ('hero_image', models.URLField(max_length=500)),
                ('gallery_images', models.JSONField(default=list)),
                ('history', models.TextField()),
                ('deity', models.CharField(blank=True, max_length=200, null=True)),
                ('timings', models.CharField(blank=True, max_length=200, null=True)),
                ('best_month', models.CharField(blank=True, max_length=200, null=True)),
                ('festivals', models.JSONField(default=list)),
                ('reach', models.TextField(blank=True, null=True)),
                ('architecture', models.TextField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='api.district')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('custom_name', models.CharField(blank=True, max_length=200, null=True)),
                ('custom_tagline', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_slides', to='api.place')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
